"""Инициализция базы данных

Revision ID: ef025e520b1b
Revises: 
Create Date: 2024-05-23 15:38:01.759265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef025e520b1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moc_hotels.csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('rooms_quantity', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_id'), 'moc_hotels.csv', ['id'], unique=False)
    op.create_table('moc_users.csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'moc_users.csv', ['id'], unique=False)
    op.create_table('moc_rooms.csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['moc_hotels.csv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'moc_rooms.csv', ['id'], unique=False)
    op.create_table('moc_bookings.csv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), sa.Computed('(date_from - date_to) * price', ), nullable=True),
    sa.Column('total_days', sa.Integer(), sa.Computed('date_from - date_to', ), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['moc_rooms.csv.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['moc_users.csv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'moc_bookings.csv', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='moc_bookings.csv')
    op.drop_table('moc_bookings.csv')
    op.drop_index(op.f('ix_rooms_id'), table_name='moc_rooms.csv')
    op.drop_table('moc_rooms.csv')
    op.drop_index(op.f('ix_users_id'), table_name='moc_users.csv')
    op.drop_table('moc_users.csv')
    op.drop_index(op.f('ix_hotels_id'), table_name='moc_hotels.csv')
    op.drop_table('moc_hotels.csv')
    # ### end Alembic commands ###
